import { backgroundImages } from 'polished';

/** @type {import('tailwindcss').Config} */
export default {
  darkMode: ['class'],
  content: ['./*.{html,js,ts,tsx}', './src/**/*.{html,js,ts,tsx}'],
  theme: {
    extend: {
      borderRadius: {
        lg: 'var(--radius)',
        md: 'calc(var(--radius) - 2px)',
        sm: 'calc(var(--radius) - 4px)',
      },
      colors: {
        transparent: 'transparent',
        primary: {
          100: '#b9ecd5',
          200: '#8be0b9',
          300: '#45cd8e',
          400: '#2dc780',
          500: '#16C172',
          600: '#14ae67',
          700: '#129a5b',
          800: '#0d7444',
          900: '#073a22',
        },
        accent: {
          100: '#e7a5ca',
          200: '#da79af',
          300: '#ce4c95',
          400: '#c83587',
          500: '#c21f7a',
          600: '#af1c6e',
          700: '#9b1962',
          800: '#881655',
          900: '#61103d',
        },
        sucess: '#34D399',
        alert: '#F87171',
        boxType: {
          bug: {
            light: '#ebf3da',
            mediumLight: '#d1e5a5',
            default: '#8CB230',
            mediumDark: '#7fa82c',
            dark: '#7b9d2e',
          },
          dark: {
            light: '#dadadd',
            mediumLight: '#b0b0b6',
            default: '#58575F',
            mediumDark: '#505157',
            dark: '#505055',
          },
          dragon: {
            light: '#cce3f8',
            mediumLight: '#8ab5e8',
            default: '#0F6AC0',
            mediumDark: '#0e61b4',
            dark: '#0e61ae',
          },
          electric: {
            light: '#fff5da',
            mediumLight: '#ffdfa2',
            default: '#f9a825',
            mediumDark: '#e19322',
            dark: '#e09021',
          },
          fairy: {
            light: '#fae4f1',
            mediumLight: '#f2afd9',
            default: '#ED6EC7',
            mediumDark: '#d564b4',
            dark: '#d55fae',
          },
          fighting: {
            light: '#ffccd7',
            mediumLight: '#ff9ba7',
            default: '#FD4363',
            mediumDark: '#e03e58',
            dark: '#e03b55',
          },
          fire: {
            light: '#fcdcdc',
            mediumLight: '#f2a2a2',
            default: '#d32f2f',
            mediumDark: '#c12b2b',
            dark: '#ba2929',
          },
          flying: {
            light: '#e0f2fd',
            mediumLight: '#a3d4f9',
            default: '#29b6f6',
            mediumDark: '#25a2da',
            dark: '#249fd1',
          },
          ghost: {
            light: '#e0e4f3',
            mediumLight: '#b0b8e0',
            default: '#556AAE',
            mediumDark: '#4e629f',
            dark: '#4d609c',
          },
          grass: {
            light: '#dbeadd',
            mediumLight: '#adc8a6',
            default: '#357a38',
            mediumDark: '#316f33',
            dark: '#306d32',
          },
          ground: {
            light: '#ffece5',
            mediumLight: '#ffcbb3',
            default: '#DD7748',
            mediumDark: '#c66b41',
            dark: '#c86a40',
          },
          ice: {
            light: '#e7f9f8',
            mediumLight: '#b0ebec',
            default: '#26c6da',
            mediumDark: '#22b2c4',
            dark: '#21abb8',
          },
          normal: {
            light: '#eff1f4',
            mediumLight: '#cfd3da',
            default: '#9DA0AA',
            mediumDark: '#8c8e98',
            dark: '#8d8f99',
          },
          poison: {
            light: '#f0dcf6',
            mediumLight: '#d3a6e9',
            default: '#A552CC',
            mediumDark: '#9549bb',
            dark: '#944ab6',
          },
          psychic: {
            light: '#fde3e8',
            mediumLight: '#f3a3b4',
            default: '#e91e63',
            mediumDark: '#cc1c57',
            dark: '#cc1a54',
          },
          rock: {
            light: '#e8dcd6',
            mediumLight: '#b89b90',
            default: '#6d4c41',
            mediumDark: '#62433a',
            dark: '#614239',
          },
          steel: {
            light: '#e2edf4',
            mediumLight: '#a8c4d5',
            default: '#416688',
            mediumDark: '#3a5c7c',
            dark: '#3b5c79',
          },
          water: {
            light: '#d9ebfb',
            mediumLight: '#91c8f7',
            default: '#0288d1',
            mediumDark: '#027dbd',
            dark: '#0279b8',
          },
        },
        backgroundCard: {
          bug: {
            light: '#e7f5e8',
            mediumLight: '#d2ebd4',
            default: '#8BD674',
            mediumDark: '#82c66a',
            dark: '#7dbf66',
          },
          dark: {
            light: '#e6e6e7',
            mediumLight: '#c4c4c6',
            default: '#6F6E78',
            mediumDark: '#64646d',
            dark: '#62626b',
          },
          dragon: {
            light: '#e6e9f2',
            mediumLight: '#b4bcd8',
            default: '#7383B9',
            mediumDark: '#6976a7',
            dark: '#6773a7',
          },
          electric: {
            light: '#fffae8',
            mediumLight: '#ffe9a4',
            default: '#fdd835',
            mediumDark: '#e5c02f',
            dark: '#e4c32e',
          },
          fairy: {
            light: '#fceaf7',
            mediumLight: '#f3c2e8',
            default: '#EC8FE6',
            mediumDark: '#d27ec9',
            dark: '#d27dc9',
          },
          fighting: {
            light: '#ffe8ed',
            mediumLight: '#ffb3c2',
            default: '#FB91A3',
            mediumDark: '#e0808e',
            dark: '#e17f8f',
          },
          fire: {
            light: '#fde3df',
            mediumLight: '#f6b3a8',
            default: '#F3634E',
            mediumDark: '#d75845',
            dark: '#d65545',
          },
          flying: {
            light: '#e8f7fd',
            mediumLight: '#c3e6fb',
            default: '#7ACFF7',
            mediumDark: '#6fc3e2',
            dark: '#6eb6d9',
          },
          ghost: {
            light: '#e8e6f4',
            mediumLight: '#c5c1e7',
            default: '#8571BE',
            mediumDark: '#7967a8',
            dark: '#7764a8',
          },
          grass: {
            light: '#e5f3e8',
            mediumLight: '#c7e3c6',
            default: '#4caf50',
            mediumDark: '#469d49',
            dark: '#449949',
          },
          ground: {
            light: '#fff2ee',
            mediumLight: '#ffc7ba',
            default: '#ffab91',
            mediumDark: '#e69e80',
            dark: '#e69b80',
          },
          ice: {
            light: '#f0fbfb',
            mediumLight: '#c7f3f3',
            default: '#6DF6E5',
            mediumDark: '#63dbc9',
            dark: '#63dac8',
          },
          normal: {
            light: '#f3f4f6',
            mediumLight: '#d9dadf',
            default: '#B5B9C4',
            mediumDark: '#a6a9b0',
            dark: '#a3a7b0',
          },
          poison: {
            light: '#f4e7f4',
            mediumLight: '#dbb3e1',
            default: '#B97FC9',
            mediumDark: '#a977b2',
            dark: '#a16fae',
          },
          psychic: {
            light: '#ffe9ea',
            mediumLight: '#f8b5b8',
            default: '#FA7179',
            mediumDark: '#dd636a',
            dark: '#dc6268',
          },
          rock: {
            light: '#f3eeec',
            mediumLight: '#d8c7c3',
            default: '#bcaaa4',
            mediumDark: '#a3948f',
            dark: '#a5938e',
          },
          steel: {
            light: '#f1f5f7',
            mediumLight: '#d0e0e8',
            default: '#88a0b5',
            mediumDark: '#7b8fa1',
            dark: '#7990a1',
          },
          water: {
            light: '#e5f1fd',
            mediumLight: '#b0d7fa',
            default: '#4AA5F7',
            mediumDark: '#4393d8',
            dark: '#4394da',
          },
        },
        sidebar: {
          DEFAULT: 'hsl(var(--sidebar-background))',
          foreground: 'hsl(var(--sidebar-foreground))',
          primary: 'hsl(var(--sidebar-primary))',
          'primary-foreground': 'hsl(var(--sidebar-primary-foreground))',
          accent: 'hsl(var(--sidebar-accent))',
          'accent-foreground': 'hsl(var(--sidebar-accent-foreground))',
          border: 'hsl(var(--sidebar-border))',
          ring: 'hsl(var(--sidebar-ring))',
        },
      },
      backgroundImage: {
        'region-kanto': 'url("/src/assets/regions/kanto.png")',
        'region-johto': 'url("/src/assets/regions/johto.png")',
        'region-hoenn': 'url("/src/assets/regions/hoenn.png")',
        'region-sinnoh': 'url("/src/assets/regions/sinnoh.png")',
        'region-unova': 'url("/src/assets/regions/unova.png")',
        'region-alola': 'url("/src/assets/regions/alola.png")',
        'region-galar': 'url("/src/assets/regions/galar.png")',
        'region-kalos': 'url("/src/assets/regions/kalos.png")',
        'region-paldea': 'url("/src/assets/regions/paldea.png")',
      },
      transitionTimingFunction: {
        'custom-bezier': 'cubic-bezier(0.165, 0.84, 0.44, 1)',
      },
      keyframes: {
        'surge-in': {
          '0%': { transform: 'translateY(80%)', opacity: 0 },
          '100%': { transform: 'translateY(0%)', opacity: 100 },
        },
      },
      animation: {
        'surge-in-bottom': 'surge-in 1s ease-in-out forwards',
      },
    },
  },
  plugins: [require('tailwindcss-animate')],
};
